### ISSUE TITLE
Responsiveness of charts in "Kompania" page

### ISSUE THREAD

**Issue by KosovareS** [opendatakosovo/e-prokurimi#22]
When opening "Kompania" page and clicking on a company that we have searched for, are displaying three charts with the information of that company. 
And these charts are not responsive.

<img width="601" alt="screen shot 2017-10-30 at 10 54 00 am" src="https://user-images.githubusercontent.com/16719237/32164905-27c9fe4e-bd61-11e7-95e4-bded5a5da5d3.png">

**Comment by egzontina** [comment]
@KosovareS
