### ISSUE TITLE
"Export to CSV" button in Kompania page is not functional

### ISSUE THREAD

**Issue by KosovareS** [opendatakosovo/e-prokurimi#23]
<img width="232" alt="screen shot 2017-10-31 at 2 51 43 pm" src="https://user-images.githubusercontent.com/16719237/32227240-1c809738-be4b-11e7-9efb-902cffe06b20.png">

**Comment by egzontina** [comment]
@KosovareS

**Comment by KosovareS** [comment]
@egzontina this is not completed because the file that I can download is TextEdit Document and the requirement is to download as CSV.
See pics attached:
<img width="1271" alt="screen shot 2017-11-01 at 9 15 40 am" src="https://user-images.githubusercontent.com/16719237/32265919-7c721208-bee5-11e7-851a-b9df4d19c6d1.png">
<img width="607" alt="screen shot 2017-11-01 at 9 18 12 am" src="https://user-images.githubusercontent.com/16719237/32265962-a0ec3d0c-bee5-11e7-9dad-b3f043ca15aa.png">
